services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: content_system_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - content_system
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: content_system_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: content_system
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: content_system
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - content_system

  nginx:
    image: nginx:alpine
    container_name: content_system_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - content_system
    depends_on:
      - app

volumes:
  mysql_data:
    driver: local

networks:
  content_system:
    driver: bridge
